drivers: scsi/ufshcd: remove an unused variable
this fixes the mismerge in d30e79d3d6212cd4d50b4e8f26c81445cfc9d078

../drivers/scsi/ufs/ufshcd.c:2006:7: error: unused variable 'flush_result' [-Werror,-Wunused-variable]
        bool flush_result;
             ^

Signed-off-by: CloudedQuartz <ravenklawasd@gmail.com>
Signed-off-by: KyuoFoxHuyu <88403766@qq.com>